/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Lecture {
  'id' : LectureId,
  'title' : string,
  'topic' : string,
  'description' : string,
  'videoFile' : ExternalBlob,
  'uploadedAt' : bigint,
}
export type LectureId = bigint;
export interface LectureInput {
  'title' : string,
  'topic' : string,
  'description' : string,
  'videoFile' : ExternalBlob,
}
export interface Note {
  'id' : NoteId,
  'title' : string,
  'topic' : string,
  'file' : ExternalBlob,
  'description' : string,
  'uploadedAt' : bigint,
}
export type NoteId = bigint;
export interface NoteInput {
  'title' : string,
  'topic' : string,
  'file' : ExternalBlob,
  'description' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLecture' : ActorMethod<[LectureId], undefined>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLecture' : ActorMethod<[LectureId], [] | [Lecture]>,
  'getNote' : ActorMethod<[NoteId], [] | [Note]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLectures' : ActorMethod<[], Array<Lecture>>,
  'listNotes' : ActorMethod<[], Array<Note>>,
  'uploadLecture' : ActorMethod<[LectureInput], Lecture>,
  'uploadNote' : ActorMethod<[NoteInput], Note>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];