/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LectureId = IDL.Nat;
export const NoteId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Lecture = IDL.Record({
  'id' : LectureId,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const LectureInput = IDL.Record({
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLecture' : IDL.Func([LectureId], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLecture' : IDL.Func([LectureId], [IDL.Opt(Lecture)], ['query']),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLectures' : IDL.Func([], [IDL.Vec(Lecture)], ['query']),
  'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'uploadLecture' : IDL.Func([LectureInput], [Lecture], []),
  'uploadNote' : IDL.Func([NoteInput], [Note], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LectureId = IDL.Nat;
  const NoteId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Lecture = IDL.Record({
    'id' : LectureId,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const LectureInput = IDL.Record({
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLecture' : IDL.Func([LectureId], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLecture' : IDL.Func([LectureId], [IDL.Opt(Lecture)], ['query']),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLectures' : IDL.Func([], [IDL.Vec(Lecture)], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'uploadLecture' : IDL.Func([LectureInput], [Lecture], []),
    'uploadNote' : IDL.Func([NoteInput], [Note], []),
  });
};

export const init = ({ IDL }) => { return []; };